### ISSUE TITLE
Macros should record find operations

### ISSUE THREAD

**Issue by xps** [xps/VSTextMacros#1]
As suggested by someone on [StackOverflow](http://stackoverflow.com/questions/12062515/can-i-record-play-macros-in-visual-studio-2012/13353364#comment18305662_13353364), find operations should be recorded as they allow reaching text that is hard/impossible to get to via cursor moves.

This should probably include Find / Incremental Find, and Find Next /  Find Previous operations.

**Comment by Bradley-Ford** [comment]
+1 to the F3 solution. That is exactly how I use macros in Notepad++.. 

- Find the item you need
- Record marco: Press F3 find the next one. Do the edit, move the cursor to after the found item. Done

Now the marco with find the next time and edit it each time you replay it.. I can't see the use of this plug in with out that function.

**Comment by xps** [comment]
I was just told that Microsoft's macro extension could record find operations.
Would be worth it to have a look at their code and see if we can implement it:
https://github.com/Microsoft/VS-Macros

**Comment by peterthomastlc** [comment]
> I was just told that Microsoft's macro extension could record find operations.
> Would be worth it to have a look at their code and see if we can implement it:
> https://github.com/Microsoft/VS-Macros

I just installed Microsoft's VS-Macros vsix in VS2019.
It seems that it *doesn't* record find operations.
One question though - if Microsoft's version of macros works in VS2013 and later as they claim (and I can verify that it runs in VS2019), why do we need this extension?

**Comment by xps** [comment]
Thanks for the feedback on Microsoft's extension.

This extension existed before the Microsoft one, so that's why it exists.

Some people prefer to use this one as it is reportedly faster than Microsoft's.

**Comment by viniciusvillas** [comment]
> Some people prefer to use this one as it is reportedly faster than Microsoft's.

Yeap. MS's one is unbearably slow for daily use, which is weird, as their embedded macro functionality on previous VS versions was great - kinda like this one. The missing F3/Find recording on this extension is really a must have. I did fiddle with the code a little bit to try to intercept the find commands, but to no avail. :(

**Comment by viniciusvillas** [comment]
Hey @xps , I just added support for it making some very minor changes using DTE. I'm not really sure what kind of collateral effects we can get by doing it this way, but it finally works! :)
https://github.com/viniciusvillas/VSTextMacros/commit/45ad5db9679db49261be2e44e56b26e885675f3c

**Comment by xps** [comment]
Hey @viniciusvillas, that's awesome, thank you! Tested and it seems to work great.

Would you like to submit a pull request? If not, I can just cherry-pick the commit.
