### ISSUE TITLE
Can't install update

### ISSUE THREAD

**Issue by Andyriod** [xps/VSTextMacros#12]
I can't update to the lastest version!
I get the following error:

The 'VSTextMacrosPackage' package did not load correctly

Any Idea?

**Comment by xps** [comment]
Seems like a few people are having the problem, but I have no idea why.
Which version of Visual Studio are you using?
Is there a log reference in the error message, from which you could get more info?
Can you try uninstalling the extension, downloading the vsix from the extension gallery, and installing from that? I've sometimes had problems installing from Visual Studio itself, not sure why.
I just tested reinstalling on my VS2013 and it's working fine for me.

**Comment by scott14468** [comment]
Hi,
I too have the same problem.  I am running VS2015 Microsoft Visual Studio Professional 2012
Version 11.0.61030.00 Update 4
Microsoft .NET Framework
Version 4.5.51209

Installed Version: Professional

LightSwitch for Visual Studio 2012   04938-141-0272737-02314
Microsoft LightSwitch for Visual Studio 2012

Office Developer Tools   04938-141-0272737-02314
Microsoft Office Developer Tools

Team Explorer for Visual Studio 2012   04938-141-0272737-02314
Microsoft Team Explorer for Visual Studio 2012

Visual Basic 2012   04938-141-0272737-02314
Microsoft Visual Basic 2012

Visual C# 2012   04938-141-0272737-02314
Microsoft Visual C# 2012

Visual C++ 2012   04938-141-0272737-02314
Microsoft Visual C++ 2012

Visual F# 2012   04938-141-0272737-02314
Microsoft Visual F# 2012

Visual Studio 2012 Code Analysis Spell Checker   04938-141-0272737-02314
Microsoft® Visual Studio® 2012 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

AnkhSVN - Subversion Support for Visual Studio   2.5.12703.45
AnkhSVN - Subversion Support for Visual Studio 2.5.12703.45 
 * Ankh.Package 2.5.12703.45
 * Subversion 1.8.13 via SharpSvn 1.8013.3694.107

SharpSvn is linked to: Apr 1.5.1, Apr-util 1.5.4, Cyrus Sasl 2.1.25, eXpat 2.1.0, OpenSSL 1.0.2d 9 Jul 2015, serf 1.3.8, SQLite 3.7.17, Subversion 1.8.13-SharpSvn-1.8.13, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.64.0(SharpSvn)

ASP.NET and Web Tools   2012.3.41009
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

InstallShield Limited Edition   
InstallShield. For more information visit the Flexera Software website at <http://www.FlexeraSoftware.com>. Copyright © 2013 Flexera Software LLC. All Rights Reserved.

NuGet Package Manager   2.8.60318.667
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.0
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   11.1.20828.01
Microsoft SQL Server Data Tools

Text Macros for Visual Studio 2012/2013/2015   1.6
Brings back text-editing macro support in Visual Studio 2012/2013/2015

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type.

================================================
Here's the XML log content that the error message refers to:

46  Begin package load [VSTextMacrosPackage] {6D613D99-E83F-4532-A1D8-E188E419460C}  VisualStudio 2015/08/03 13:44:30.901 
47 ERROR CreateInstance failed for package [VSTextMacrosPackage] {6D613D99-E83F-4532-A1D8-E188E419460C} 80070002 VisualStudio 2015/08/03 13:44:30.905 
48 ERROR End package load [VSTextMacrosPackage] {6D613D99-E83F-4532-A1D8-E188E419460C} 80004005 - E_FAIL VisualStudio 2015/08/03 13:44:30.905 

Thanks,
Scott

**Comment by xps** [comment]
Hi, and thanks for the reports.

I have released a new version that includes the required libraries (VS 2012 SDK) in the package, so that hopefully solves the problem. I have successfully tested it in a clean VM with just VS 2012 and it worked, but it would be great if you could confirm that it works for you too.

The new version (1.7) is up on the extension gallery.

**Comment by scott14468** [comment]
Hi Xavier,

That seems to have fixed it.  I've installed it on two PCs without any problems.

Thanks,
Scott


---- Xavier Poinas <notifications@github.com> wrote: 

=============
Hi, and thanks for the reports.

I have released a new version that includes the required libraries (VS 2012 SDK) in the package, so that hopefully solves the problem. I have successfully tested it in a clean VM with just VS 2012 and it worked, but it would be great if you could confirm that it works for you too.

The new version (1.7) is up on the extension gallery.

---

**Comment by xps** [comment]
Glad to hear that! Thanks for getting back to me, I'll close this issue.
