### ISSUE TITLE
F3 to continue search doesn't work

### ISSUE THREAD

**Issue by mpietras** [xps/VSTextMacros#16]
VS2015.  Search for some text, get some replacement text in the clipboard, start recording a macro, paste, F3, stop recording macro, playback macro... the F3 find next doesn't happen.

**Comment by xps** [comment]
HI, and thanks for reporting this. I will close it as a duplicate of this issue:
https://github.com/xps/VSTextMacros/issues/1

Unfortunately as you'll see in the linked conversation, there are technical challenges to implement this.
