### ISSUE TITLE
Macro won't save

### ISSUE THREAD

**Issue by nhdinh** [xps/VSTextMacros#17]
Hi,
After finished recording a macro, I choose save macro but the error occurred like below:

> VSTextMacros.Model.SavedMacro cannot be serialized because it does not have a parameterless constructor.

Thanks
Hung Dinh

**Comment by nhdinh** [comment]
I am on VS 2015 (Pro)

**Comment by xps** [comment]
Oops, my bad, I must have refactored this code and was satisfied that it still compiled so I didn't test, shame on me. Thanks for the fix, I have released a new version.
