### ISSUE TITLE
Allow a keyboard shortcut to be assigned to a saved macro

### ISSUE THREAD

**Issue by rusql** [xps/VSTextMacros#19]
This would be a great feature to allow quick access to play commonly used macros. Even if it were something simple like _Ctl+m+1_ plays the first saved macro.

**Comment by xps** [comment]
Thanks for the feedback. I will close as a duplicate of https://github.com/xps/VSTextMacros/issues/7. See the the suggestion I made on that thread can help in the mean time.

**Comment by rusql** [comment]
Thank you. Sorry that I missed that this was already suggested.
