### ISSUE TITLE
Macros don't record clippboard Copy operations

### ISSUE THREAD

**Issue by maadlog** [xps/VSTextMacros#21]
Given two lines:
**foobar
bazbar**
recording a macro that selects the first 3 characters and copies them at the end of the string, yields the following result in the first line:
 _foobar_ -> foobarfoo

Replaying it in the second line should yield "bazbarbaz", instead it yields the following:
 _bazbar_ -> bazbar**foo**

Apparently, it records the Ctrl+V Paste actions, but ignores the Ctrl+C Copy

Cheers!

EDIT: Workspace is VS2013 Update 5

**Comment by ygoe** [comment]
Works for me in VS 2015. Both variants, Ctrl+C/Ctrl+V and Ctrl+Ins/Shift+Ins are recorded and played back properly.

**Comment by xps** [comment]
It is probably a problem with the Productivity Power Tools extension, see [this issue][1] for more info.
I'll close as a duplicate, feel free to reopen if you have a different issue.

I also updated the readme to mention this.

  [1]: https://github.com/xps/VSTextMacros/issues/14
