### ISSUE TITLE
Add official support for Visual Studio 2017

### ISSUE THREAD

**Issue by ygoe** [xps/VSTextMacros#22]
There's one report on the Marketplace page that says it already works, only the manifest needs to be updated. I have just tried it and it works well in VS 2017. (The compatibility warning on installation is normal and can be ignored. Other extensions have it as well.)

**Comment by xps** [comment]
I thought I could just update the target version in the manifest file. Indeed it installs and works fine on VS 2017 (albeit with a warning). However, the Marketplace does not let me upload the VSIX.

> This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK. Please make sure to update your references and try uploading again. Note: you'll also need to add Prerequisites to your extension.vsixmanifest.

I guess I'll have to update the manifest to v3, hopefully while maintaining backward compatibility.

**Comment by xps** [comment]
I updated the project and the version now online on the marketplace supports VS 2017.
