### ISSUE TITLE
Add a link to this repository on the Marketplace page

### ISSUE THREAD

**Issue by ygoe** [xps/VSTextMacros#23]
Add a link to this repository on the VS Marketplace page so it's (even) easier to find.

(Sorry, it doesn't seem to be in the manifest file, that's an admin task for the publisher.)

**Comment by xps** [comment]
Thanks for the suggestion. There is already a link:

 > An open-source [[GitHub][1]] extension ...

Maybe there is a better location for that link?

  [1]: https://github.com/xps/VSTextMacros

**Comment by ygoe** [comment]
My description became unclear through my edit. Most other extensions have the GitHub link in the right column along with the other metadata, not just in the description text. There must be a dedicated field in the extension edit page where you can enter the GitHub URL. Mine looks like this:

> ![grafik](https://cloud.githubusercontent.com/assets/868315/25313163/bba35638-2829-11e7-9743-60b92616055b.png)

The result then looks like this:

> ![grafik](https://cloud.githubusercontent.com/assets/868315/25313167/dd4d9d16-2829-11e7-8fc5-d0a693015ec0.png)

**Comment by xps** [comment]
Thanks for the tip! Done
