### ISSUE TITLE
Does not record Ctrl or Shift combinations

### ISSUE THREAD

**Issue by talbotsk** [xps/VSTextMacros#26]
Can not record Ctrl+], Ctrl+Shift+], etc. key combinations. Please fix it. Thank you very much for your project! :-)

**Comment by xps** [comment]
Sorry for the late response. This extension does not actually record key presses but rather, it records Visual Studio commands. So Shift and Ctrl aren't recorded but the commands you are trying to run with these shortcuts could possibly be added to the list of commands that can be recorded.

**Comment by xps** [comment]
Fixed it 2c189cb5.
