### ISSUE TITLE
MsgBox isn't supported

### ISSUE THREAD

**Issue by sarrows** [xps/VSTextMacros#31]
The function MsgBox() is not supported in js file.
I like to write codes instead of recording and sometimes I need to see variable's value by popping up a message box with text shown.

**Comment by xps** [comment]
Hi, I'm sorry but don't I understand what you mean. There is a function called alert() in JavaScript, but I'm not sure I understand what this has to do with macros.

**Comment by sarrows** [comment]
Hi, thanks for reply!
I'm sorry for not making it clear...
Here is the steps:
1. [Macro Explorer]->[Samples]->Right-click "Current“ and select open->File "Current.js" is opened.
2. Input text:
    alert("test alert.");
   Then save and paly. Error message is displayed, means that the function is not supported.
I think alert or other such functions will be very helpful for users.

**Comment by xps** [comment]
I'm sorry but this extension does not provide a "Macro Explorer", and macros in this extension aren't recorded in JavaScript, but in XML. Are you sure this is the extension you are using?

**Comment by sarrows** [comment]
I'm so sorry for bothering you so much!
You are right, I've mistaken your project as "https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MacrosforVisualStudio".
How ridiculous I am ...
Thanks for your reply again!

**Comment by xps** [comment]
No worries at all, I hope you find a solution to your problem.
