### ISSUE TITLE
Could VSTextMacros be used to change Ctrl+C to copy just the current word, and not the whole line?

### ISSUE THREAD

**Issue by daryllabar** [xps/VSTextMacros#32]
I have a SO question that I believe can be solved with this plugin.  Could you verify that it could for me?

https://stackoverflow.com/questions/55942005/how-to-change-ctrlc-in-visual-studio-2017-to-copy-word-not-entire-line?noredirect=1#comment98537885_55942005

Thanks!

**Comment by xps** [comment]
I think you could bind a keyboard shortcut to a macro that copies the current word, but binding it to Ctrl+C would be problematic (macros aren't smart enough to distinguish the case where the normal copy behavior should be used).
