### ISSUE TITLE
Installation not working on VSC 1.73.1 / 2022-11-09

### ISSUE THREAD

**Issue by kingdase** [xps/VSTextMacros#46]
Hi,  installation from VSIX is not working.

Error message is: "extension/package.json not found inside zip"

Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No

**Comment by xps** [comment]
Hi,

This extension is for Visual Studio, not for Visual Studio Code.
