### ISSUE TITLE
Is there a way to add more than 5 saved macros?

### ISSUE THREAD

**Issue by LazieWouters** [xps/VSTextMacros#47]
Your extension is wonderful, and it makes coding easier. It would be great if it has more than 5 spaces to save macros

**Comment by xps** [comment]
You could always save as many macros as you like.
I am guessing you're referring to the number of macros that can have keybindings assigned.
I just increased that from 5 to 9 (in version 1.18).

You can still save more macros than that, but then you have to access them via the Saved Macros window.
