### ISSUE TITLE
Link to version for older VS versions (1.12) does not work

### ISSUE THREAD

**Issue by mbeiley** [xps/VSTextMacros#49]
The project mentions to use version 1.12 for VS 2012-2017, and provides a link:

https://github.com/xps/VSTextMacros/releases/download/1.12/VSTextMacros-1.12.vsix

which results in a 404 error.  Can this version still be downloaded?

**Comment by xps** [comment]
I'm not sure what happened to the release, which had disappeared, but I recreated it and the link now works again.
