### ISSUE TITLE
Feature request: Assign keyboard shortcuts to macros

### ISSUE THREAD

**Issue by jbjorge** [xps/VSTextMacros#7]
Which also implies being able to record more than one.

**Comment by xps** [comment]
Version 1.8 introduces the ability to record more than one macro.
While I haven't implemented dedicated macro shortcuts in this version, there is the option to use the following key sequence:
 - Ctrl+Shitf+M to open the saved macros window
 - Numeric keys 1 to 9 to load the n-th macro from the list as the current macro
 - Ctrl+Shift+P to replay the macro

**Comment by xps** [comment]
This was added in version 1.11
